---
- name: build image and push to docker hub play
  hosts: ansible_host
  tasks:
  - name: remove exist image
    command: docker rmi -f taedo/my-hello-world
    ignore_errors: true
  - name: build image
    command: docker build -t taedo/my-hello-world ~/hello-world
  - name: push to docker hub
    command: docker push taedo/my-hello-world

